#必填
name: test

#必填，应用版本号
version: 1.0.0

#选填，默认为honeycomb提供的favicon
favicon: ./fav.icon

#必填，域名和路径对应
url:
  - 'http://localhost/'

#绑定的ip和端口
bind:
  - 0.0.0.0:8070 #绑定所有ip地址
  # - 127.0.0.1:8080 #本地ip

#选填，控制启动几个进程来绑定该应用，默认为 1
process_num: 1

# 必填，设定应用的middleware
extensions:
  #自定义middleware的位置用户自己控制，容器获取带./的就是自定义middleware
  '/ > ./lib/test':
  '/ware/ > ./lib/ware':
  '/test/ > ./lib/test':


  #(需要执行extensions.load操作时，设置类型，分为global，process和server，控制extensions.load执行的位置)
  #自定义的middleware可以不用设定file_dir，因为可以在代码中自己处理
